version: '3.9'

services:
  #MongoDB service
  mongo_db:
    image: mongo:latest
    container_name: mongo_db_container
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db: {}